// MSCI World Index Constituents (via iShares MSCI World ETF - URTH)
// Source: https://www.ishares.com/us/products/239696/ishares-msci-world-etf
// Holdings as of: May 11, 2026
// Total equity holdings: 1311 (1308 with valid tickers)

const msciWorldConstituents = [
  { name: "NVIDIA CORP", ticker: "NVDA" },
  { name: "APPLE INC", ticker: "AAPL" },
  { name: "MICROSOFT CORP", ticker: "MSFT" },
  { name: "AMAZON.COM INC", ticker: "AMZN" },
  { name: "ALPHABET INC CLASS A", ticker: "GOOGL" },
  { name: "BROADCOM INC", ticker: "AVGO" },
  { name: "ALPHABET INC CLASS C", ticker: "GOOG" },
  { name: "META PLATFORMS INC CLASS A", ticker: "META" },
  { name: "TESLA INC", ticker: "TSLA" },
  { name: "MICRON TECHNOLOGY INC", ticker: "MU" },
  { name: "JPMORGAN CHASE & CO", ticker: "JPM" },
  { name: "ELI LILLY", ticker: "LLY" },
  { name: "ADVANCED MICRO DEVICES INC", ticker: "AMD" },
  { name: "BERKSHIRE HATHAWAY INC CLASS B", ticker: "BRKB" },
  { name: "EXXON MOBIL CORP", ticker: "XOM" },
  { name: "ASML HOLDING NV", ticker: "ASML" },
  { name: "INTEL CORPORATION CORP", ticker: "INTC" },
  { name: "WALMART INC", ticker: "WMT" },
  { name: "VISA INC CLASS A", ticker: "V" },
  { name: "JOHNSON & JOHNSON", ticker: "JNJ" },
  { name: "COSTCO WHOLESALE CORP", ticker: "COST" },
  { name: "CATERPILLAR INC", ticker: "CAT" },
  { name: "MASTERCARD INC CLASS A", ticker: "MA" },
  { name: "CISCO SYSTEMS INC", ticker: "CSCO" },
  { name: "LAM RESEARCH CORP", ticker: "LRCX" },
  { name: "NETFLIX INC", ticker: "NFLX" },
  { name: "ABBVIE INC", ticker: "ABBV" },
  { name: "CHEVRON CORP", ticker: "CVX" },
  { name: "APPLIED MATERIAL INC", ticker: "AMAT" },
  { name: "BANK OF AMERICA CORP", ticker: "BAC" },
  { name: "UNITEDHEALTH GROUP INC", ticker: "UNH" },
  { name: "PROCTER & GAMBLE", ticker: "PG" },
  { name: "ORACLE CORP", ticker: "ORCL" },
  { name: "COCA-COLA", ticker: "KO" },
  { name: "GE AEROSPACE", ticker: "GE" },
  { name: "PALANTIR TECHNOLOGIES INC CLASS A", ticker: "PLTR" },
  { name: "HSBC HOLDINGS PLC", ticker: "HSBA" },
  { name: "HOME DEPOT INC", ticker: "HD" },
  { name: "GE VERNOVA INC", ticker: "GEV" },
  { name: "ROCHE PS PAR AG", ticker: "ROP" },
  { name: "GOLDMAN SACHS GROUP INC", ticker: "GS" },
  { name: "ASTRAZENECA PLC", ticker: "AZN" },
  { name: "PHILIP MORRIS INTERNATIONAL INC", ticker: "PM" },
  { name: "NOVARTIS AG", ticker: "NOVN" },
  { name: "MERCK & CO INC", ticker: "MRK" },
  { name: "TEXAS INSTRUMENT INC", ticker: "TXN" },
  { name: "ROYAL BANK OF CANADA", ticker: "RY" },
  { name: "QUALCOMM INC", ticker: "QCOM" },
  { name: "NESTLE SA", ticker: "NESN" },
  { name: "SHELL PLC", ticker: "SHEL" },
  { name: "KLA CORP", ticker: "KLAC" },
  { name: "SIEMENS N AG", ticker: "SIE" },
  { name: "RTX CORP", ticker: "RTX" },
  { name: "LINDE PLC", ticker: "LIN" },
  { name: "WELLS FARGO", ticker: "WFC" },
  { name: "MORGAN STANLEY", ticker: "MS" },
  { name: "CITIGROUP INC", ticker: "C" },
  { name: "BHP GROUP LTD", ticker: "BHP" },
  { name: "COMMONWEALTH BANK OF AUSTRALIA", ticker: "CBA" },
  { name: "ANALOG DEVICES INC", ticker: "ADI" },
  { name: "INTERNATIONAL BUSINESS MACHINES CO", ticker: "IBM" },
  { name: "MITSUBISHI UFJ FINANCIAL GROUP INC", ticker: "8306" },
  { name: "PEPSICO INC", ticker: "PEP" },
  { name: "VERIZON COMMUNICATIONS INC", ticker: "VZ" },
  { name: "NEXTERA ENERGY INC", ticker: "NEE" },
  { name: "MCDONALDS CORP", ticker: "MCD" },
  { name: "WALT DISNEY", ticker: "DIS" },
  { name: "BOEING", ticker: "BA" },
  { name: "SEAGATE TECHNOLOGY HOLDINGS PLC", ticker: "STX" },
  { name: "BANCO SANTANDER SA", ticker: "SAN" },
  { name: "TORONTO DOMINION", ticker: "TD" },
  { name: "TOTALENERGIES", ticker: "TTE" },
  { name: "SAP", ticker: "SAP" },
  { name: "SCHNEIDER ELECTRIC", ticker: "SU" },
  { name: "AT&T INC", ticker: "T" },
  { name: "WESTERN DIGITAL CORP", ticker: "WDC" },
  { name: "AMGEN INC", ticker: "AMGN" },
  { name: "AMERICAN EXPRESS", ticker: "AXP" },
  { name: "TOYOTA MOTOR CORP", ticker: "7203" },
  { name: "PALO ALTO NETWORKS INC", ticker: "PANW" },
  { name: "THERMO FISHER SCIENTIFIC INC", ticker: "TMO" },
  { name: "ALLIANZ", ticker: "ALV" },
  { name: "ABB LTD", ticker: "ABBN" },
  { name: "CORNING INC", ticker: "GLW" },
  { name: "TJX INC", ticker: "TJX" },
  { name: "SALESFORCE INC", ticker: "CRM" },
  { name: "GILEAD SCIENCES INC", ticker: "GILD" },
  { name: "SIEMENS ENERGY N AG", ticker: "ENR" },
  { name: "EATON PLC", ticker: "ETN" },
  { name: "BLACKROCK INC", ticker: "BLK" },
  { name: "UNION PACIFIC CORP", ticker: "UNP" },
  { name: "NOVO NORDISK CLASS B", ticker: "NOVO B" },
  { name: "DEERE", ticker: "DE" },
  { name: "UBER TECHNOLOGIES INC", ticker: "UBER" },
  { name: "INTUITIVE SURGICAL INC", ticker: "ISRG" },
  { name: "IBERDROLA SA", ticker: "IBE" },
  { name: "AMPHENOL CORP CLASS A", ticker: "APH" },
  { name: "TOKYO ELECTRON LTD", ticker: "8035" },
  { name: "CHARLES SCHWAB CORP", ticker: "SCHW" },
  { name: "WELLTOWER INC", ticker: "WELL" },
  { name: "MARVELL TECHNOLOGY INC", ticker: "MRVL" },
  { name: "PFIZER INC", ticker: "PFE" },
  { name: "ARISTA NETWORKS INC", ticker: "ANET" },
  { name: "HITACHI LTD", ticker: "6501" },
  { name: "CONOCOPHILLIPS", ticker: "COP" },
  { name: "UBS GROUP AG", ticker: "UBSG" },
  { name: "ABBOTT LABORATORIES", ticker: "ABT" },
  { name: "ADVANTEST CORP", ticker: "6857" },
  { name: "ROLLS-ROYCE HOLDINGS PLC", ticker: "RR." },
  { name: "HONEYWELL INTERNATIONAL INC", ticker: "HON" },
  { name: "CROWDSTRIKE HOLDINGS INC CLASS A", ticker: "CRWD" },
  { name: "SOFTBANK GROUP CORP", ticker: "9984" },
  { name: "LVMH", ticker: "MC" },
  { name: "PROLOGIS REIT INC", ticker: "PLD" },
  { name: "VERTIV HOLDINGS CLASS A", ticker: "VRT" },
  { name: "S&P GLOBAL INC", ticker: "SPGI" },
  { name: "NEWMONT", ticker: "NEM" },
  { name: "SUMITOMO MITSUI FINANCIAL GROUP IN", ticker: "8316" },
  { name: "BRITISH AMERICAN TOBACCO", ticker: "BATS" },
  { name: "SONY GROUP CORP", ticker: "6758" },
  { name: "BOOKING HOLDINGS INC", ticker: "BKNG" },
  { name: "SHOPIFY SUBORDINATE VOTING INC CLA", ticker: "SHOP" },
  { name: "BANCO BILBAO VIZCAYA ARGENTARIA SA", ticker: "BBVA" },
  { name: "UNILEVER PLC", ticker: "ULVR" },
  { name: "LOWES COMPANIES INC", ticker: "LOW" },
  { name: "AIRBUS GROUP", ticker: "AIR" },
  { name: "RIO TINTO PLC", ticker: "RIO" },
  { name: "DEUTSCHE TELEKOM N AG", ticker: "DTE" },
  { name: "SAFRAN SA", ticker: "SAF" },
  { name: "CHUBB", ticker: "CB" },
  { name: "STARBUCKS CORP", ticker: "SBUX" },
  { name: "ENBRIDGE INC", ticker: "ENB" },
  { name: "LAIR LIQUIDE SOCIETE ANONYME POUR", ticker: "AI" },
  { name: "UNICREDIT", ticker: "UCG" },
  { name: "CVS HEALTH CORP", ticker: "CVS" },
  { name: "CAPITAL ONE FINANCIAL CORP", ticker: "COF" },
  { name: "QUANTA SERVICES INC", ticker: "PWR" },
  { name: "AIA GROUP LTD", ticker: "1299" },
  { name: "PROGRESSIVE CORP", ticker: "PGR" },
  { name: "BP PLC", ticker: "BP." },
  { name: "ALTRIA GROUP INC", ticker: "MO" },
  { name: "BRISTOL MYERS SQUIBB", ticker: "BMY" },
  { name: "VERTEX PHARMACEUTICALS INC", ticker: "VRTX" },
  { name: "PARKER-HANNIFIN CORP", ticker: "PH" },
  { name: "BNP PARIBAS SA", ticker: "BNP" },
  { name: "APPLOVIN CORP CLASS A", ticker: "APP" },
  { name: "INTUIT INC", ticker: "INTU" },
  { name: "BANK OF MONTREAL", ticker: "BMO" },
  { name: "MIZUHO FINANCIAL GROUP INC", ticker: "8411" },
  { name: "MITSUBISHI CORP", ticker: "8058" },
  { name: "ACCENTURE PLC CLASS A", ticker: "ACN" },
  { name: "LOCKHEED MARTIN CORP", ticker: "LMT" },
  { name: "COMPAGNIE FINANCIERE RICHEMONT SA", ticker: "CFR" },
  { name: "TRANE TECHNOLOGIES PLC", ticker: "TT" },
  { name: "DANAHER CORP", ticker: "DHR" },
  { name: "FAST RETAILING LTD", ticker: "9983" },
  { name: "EQUINIX REIT INC", ticker: "EQIX" },
  { name: "KEYENCE CORP", ticker: "6861" },
  { name: "HOWMET AEROSPACE INC", ticker: "HWM" },
  { name: "CANADIAN IMPERIAL BANK OF COMMERCE", ticker: "CM" },
  { name: "GLAXOSMITHKLINE", ticker: "GSK" },
  { name: "ZURICH INSURANCE GROUP AG", ticker: "ZURN" },
  { name: "ADOBE INC", ticker: "ADBE" },
  { name: "CME GROUP INC CLASS A", ticker: "CME" },
  { name: "SOUTHERN", ticker: "SO" },
  { name: "LOREAL SA", ticker: "OR" },
  { name: "CADENCE DESIGN SYSTEMS INC", ticker: "CDNS" },
  { name: "AGNICO EAGLE MINES LTD", ticker: "AEM" },
  { name: "SYNOPSYS INC", ticker: "SNPS" },
  { name: "INTESA SANPAOLO", ticker: "ISP" },
  { name: "DUKE ENERGY CORP", ticker: "DUK" },
  { name: "T MOBILE US INC", ticker: "TMUS" },
  { name: "SANOFI SA", ticker: "SAN" },
  { name: "CUMMINS INC", ticker: "CMI" },
  { name: "STRYKER CORP", ticker: "SYK" },
  { name: "BROOKFIELD CORP CLASS A", ticker: "BN" },
  { name: "BANK OF NOVA SCOTIA", ticker: "BNS" },
  { name: "INFINEON TECHNOLOGIES AG", ticker: "IFX" },
  { name: "DBS GROUP HOLDINGS LTD", ticker: "D05" },
  { name: "MEDTRONIC PLC", ticker: "MDT" },
  { name: "ENEL", ticker: "ENEL" },
  { name: "CANADIAN NATURAL RESOURCES LTD", ticker: "CNQ" },
  { name: "CONSTELLATION ENERGY CORP", ticker: "CEG" },
  { name: "SERVICENOW INC", ticker: "NOW" },
  { name: "WESTPAC BANKING CORPORATION CORP", ticker: "WBC" },
  { name: "MITSUBISHI HEAVY INDUSTRIES LTD", ticker: "7011" },
  { name: "FREEPORT MCMORAN INC", ticker: "FCX" },
  { name: "BANK OF NEW YORK MELLON CORP", ticker: "BK" },
  { name: "ING GROEP NV", ticker: "INGA" },
  { name: "COMCAST CORP CLASS A", ticker: "CMCSA" },
  { name: "INTERCONTINENTAL EXCHANGE INC", ticker: "ICE" },
  { name: "WILLIAMS INC", ticker: "WMB" },
  { name: "MITSUI LTD", ticker: "8031" },
  { name: "MCKESSON CORP", ticker: "MCK" },
  { name: "BLACKSTONE INC", ticker: "BX" },
  { name: "NATIONAL GRID PLC", ticker: "NG." },
  { name: "ELEVANCE HEALTH INC", ticker: "ELV" },
  { name: "JOHNSON CONTROLS INTERNATIONAL PLC", ticker: "JCI" },
  { name: "NATIONAL AUSTRALIA BANK LTD", ticker: "NAB" },
  { name: "FEDEX CORP", ticker: "FDX" },
  { name: "AUTOMATIC DATA PROCESSING INC", ticker: "ADP" },
  { name: "WASTE MANAGEMENT INC", ticker: "WM" },
  { name: "US BANCORP", ticker: "USB" },
  { name: "PNC FINANCIAL SERVICES GROUP INC", ticker: "PNC" },
  { name: "CIENA CORP", ticker: "CIEN" },
  { name: "CSX CORP", ticker: "CSX" },
  { name: "MARRIOTT INTERNATIONAL INC CLASS A", ticker: "MAR" },
  { name: "TOKIO MARINE HOLDINGS INC", ticker: "8766" },
  { name: "AMERICAN TOWER REIT CORP", ticker: "AMT" },
  { name: "SLB NV", ticker: "SLB" },
  { name: "MITSUBISHI ELECTRIC CORP", ticker: "6503" },
  { name: "MONDELEZ INTERNATIONAL INC CLASS A", ticker: "MDLZ" },
  { name: "BARRICK MINING CORP", ticker: "ABX" },
  { name: "SHIN ETSU CHEMICAL LTD", ticker: "4063" },
  { name: "BARCLAYS PLC", ticker: "BARC" },
  { name: "LLOYDS BANKING GROUP PLC", ticker: "LLOY" },
  { name: "SUNCOR ENERGY INC", ticker: "SU" },
  { name: "MONOLITHIC POWER SYSTEMS INC", ticker: "MPWR" },
  { name: "GENERAL DYNAMICS CORP", ticker: "GD" },
  { name: "ANZ GROUP HOLDINGS LTD", ticker: "ANZ" },
  { name: "OREILLY AUTOMOTIVE INC", ticker: "ORLY" },
  { name: "EMERSON ELECTRIC", ticker: "EMR" },
  { name: "BAE SYSTEMS PLC", ticker: "BA." },
  { name: "GLENCORE PLC", ticker: "GLEN" },
  { name: "BOSTON SCIENTIFIC CORP", ticker: "BSX" },
  { name: "AXA SA", ticker: "CS" },
  { name: "MARSH INC", ticker: "MRSH" },
  { name: "ANHEUSER-BUSCH INBEV SA", ticker: "ABI" },
  { name: "NXP SEMICONDUCTORS NV", ticker: "NXPI" },
  { name: "CANADIAN PACIFIC KANSAS CITY LTD", ticker: "CP" },
  { name: "MUENCHENER RUECKVERSICHERUNGS-GESE", ticker: "MUV2" },
  { name: "MARATHON PETROLEUM CORP", ticker: "MPC" },
  { name: "CIGNA", ticker: "CI" },
  { name: "DELL TECHNOLOGIES INC CLASS C", ticker: "DELL" },
  { name: "NORTHROP GRUMMAN CORP", ticker: "NOC" },
  { name: "3M", ticker: "MMM" },
  { name: "CRH PUBLIC LIMITED PLC", ticker: "CRH" },
  { name: "VALERO ENERGY CORP", ticker: "VLO" },
  { name: "VINCI SA", ticker: "DG" },
  { name: "REGENERON PHARMACEUTICALS INC", ticker: "REGN" },
  { name: "ITOCHU CORP", ticker: "8001" },
  { name: "LUMENTUM HOLDINGS INC", ticker: "LITE" },
  { name: "SHERWIN WILLIAMS", ticker: "SHW" },
  { name: "HILTON WORLDWIDE HOLDINGS INC", ticker: "HLT" },
  { name: "UNITED PARCEL SERVICE INC CLASS B", ticker: "UPS" },
  { name: "INVESTOR CLASS B", ticker: "INVE B" },
  { name: "FORTINET INC", ticker: "FTNT" },
  { name: "COMFORT SYSTEMS USA INC", ticker: "FIX" },
  { name: "EOG RESOURCES INC", ticker: "EOG" },
  { name: "MOODYS CORP", ticker: "MCO" },
  { name: "ROSS STORES INC", ticker: "ROST" },
  { name: "NOKIA", ticker: "NOKIA" },
  { name: "OVERSEA-CHINESE BANKING LTD", ticker: "O39" },
  { name: "PHILLIPS 66", ticker: "PSX" },
  { name: "GENERAL MOTORS", ticker: "GM" },
  { name: "MERCADOLIBRE INC", ticker: "MELI" },
  { name: "NORFOLK SOUTHERN CORP", ticker: "NSC" },
  { name: "ILLINOIS TOOL INC", ticker: "ITW" },
  { name: "HCA HEALTHCARE INC", ticker: "HCA" },
  { name: "FUJIKURA LTD", ticker: "5803" },
  { name: "AMERICAN ELECTRIC POWER INC", ticker: "AEP" },
  { name: "RECRUIT HOLDINGS LTD", ticker: "6098" },
  { name: "TC ENERGY CORP", ticker: "TRP" },
  { name: "ROYAL CARIBBEAN GROUP LTD", ticker: "RCL" },
  { name: "MANULIFE FINANCIAL CORP", ticker: "MFC" },
  { name: "TRANSDIGM GROUP INC", ticker: "TDG" },
  { name: "DIGITAL REALTY TRUST REIT INC", ticker: "DLR" },
  { name: "TRAVELERS COMPANIES INC", ticker: "TRV" },
  { name: "AIR PRODUCTS AND CHEMICALS INC", ticker: "APD" },
  { name: "COLGATE-PALMOLIVE", ticker: "CL" },
  { name: "SPOTIFY TECHNOLOGY SA", ticker: "SPOT" },
  { name: "WHEATON PRECIOUS METALS CORP", ticker: "WPM" },
  { name: "KIOXIA HOLDINGS CORP", ticker: "285A" },
  { name: "MOTOROLA SOLUTIONS INC", ticker: "MSI" },
  { name: "SIMON PROPERTY GROUP REIT INC", ticker: "SPG" },
  { name: "RHEINMETALL AG", ticker: "RHM" },
  { name: "BLOOM ENERGY CLASS A CORP", ticker: "BE" },
  { name: "MONSTER BEVERAGE CORP", ticker: "MNST" },
  { name: "ECOLAB INC", ticker: "ECL" },
  { name: "INDUSTRIA DE DISENO TEXTIL SA", ticker: "ITX" },
  { name: "NATWEST GROUP PLC", ticker: "NWG" },
  { name: "KINDER MORGAN INC", ticker: "KMI" },
  { name: "AON PLC CLASS A", ticker: "AON" },
  { name: "BAKER HUGHES CLASS A", ticker: "BKR" },
  { name: "KEYSIGHT TECHNOLOGIES INC", ticker: "KEYS" },
  { name: "MURATA MANUFACTURING LTD", ticker: "6981" },
  { name: "MACQUARIE GROUP LTD DEF", ticker: "MQG" },
  { name: "PROSUS NV CLASS N", ticker: "PRX" },
  { name: "TRUIST FINANCIAL CORP", ticker: "TFC" },
  { name: "WARNER BROS. DISCOVERY INC SERIES", ticker: "WBD" },
  { name: "TE CONNECTIVITY PLC", ticker: "TEL" },
  { name: "DEUTSCHE BANK AG", ticker: "DBK" },
  { name: "KKR AND CO INC", ticker: "KKR" },
  { name: "HOYA CORP", ticker: "7741" },
  { name: "RELX PLC", ticker: "REL" },
  { name: "ROBINHOOD MARKETS INC CLASS A", ticker: "HOOD" },
  { name: "SEMPRA", ticker: "SRE" },
  { name: "DOORDASH INC CLASS A", ticker: "DASH" },
  { name: "UNITED RENTALS INC", ticker: "URI" },
  { name: "ANGLO AMERICAN PLC", ticker: "AAL" },
  { name: "CINTAS CORP", ticker: "CTAS" },
  { name: "AIRBNB INC CLASS A", ticker: "ABNB" },
  { name: "NATIONAL BANK OF CANADA", ticker: "NA" },
  { name: "WESFARMERS LTD", ticker: "WES" },
  { name: "AUTOZONE INC", ticker: "AZO" },
  { name: "PACCAR INC", ticker: "PCAR" },
  { name: "COHERENT CORP", ticker: "COHR" },
  { name: "CANADIAN NATIONAL RAILWAY", ticker: "CNR" },
  { name: "HERMES INTERNATIONAL", ticker: "RMS" },
  { name: "CLOUDFLARE INC CLASS A", ticker: "NET" },
  { name: "AFLAC INC", ticker: "AFL" },
  { name: "ENGIE SA", ticker: "ENGI" },
  { name: "DATADOG INC CLASS A", ticker: "DDOG" },
  { name: "SOCIETE GENERALE SA", ticker: "GLE" },
  { name: "ESSILORLUXOTTICA SA", ticker: "EL" },
  { name: "LONDON STOCK EXCHANGE GROUP PLC", ticker: "LSEG" },
  { name: "REALTY INCOME REIT CORP", ticker: "O" },
  { name: "CORTEVA INC", ticker: "CTVA" },
  { name: "TERADYNE INC", ticker: "TER" },
  { name: "NORDEA BANK", ticker: "NDA FI" },
  { name: "APOLLO GLOBAL MANAGEMENT INC", ticker: "APO" },
  { name: "ENI", ticker: "ENI" },
  { name: "ROCKET LAB CORP", ticker: "RKLB" },
  { name: "VOLVO CLASS B", ticker: "VOLV B" },
  { name: "L3HARRIS TECHNOLOGIES INC", ticker: "LHX" },
  { name: "ALLSTATE CORP", ticker: "ALL" },
  { name: "DEUTSCHE BOERSE AG", ticker: "DB1" },
  { name: "FLEX LTD", ticker: "FLEX" },
  { name: "WW GRAINGER INC", ticker: "GWW" },
  { name: "BASF N", ticker: "BAS" },
  { name: "CAMECO CORP", ticker: "CCO" },
  { name: "ONEOK INC", ticker: "OKE" },
  { name: "MICROCHIP TECHNOLOGY INC", ticker: "MCHP" },
  { name: "DOMINION ENERGY INC", ticker: "D" },
  { name: "TARGA RESOURCES CORP", ticker: "TRGP" },
  { name: "TARGET CORP", ticker: "TGT" },
  { name: "AMETEK INC", ticker: "AME" },
  { name: "TAKEDA PHARMACEUTICAL LTD", ticker: "4502" },
  { name: "NUCOR CORP", ticker: "NUE" },
  { name: "ATLAS COPCO CLASS A", ticker: "ATCO A" },
  { name: "DEVON ENERGY CORP", ticker: "DVN" },
  { name: "ROCKWELL AUTOMATION INC", ticker: "ROK" },
  { name: "SUMITOMO ELECTRIC INDUSTRIES LTD", ticker: "5802" },
  { name: "CAIXABANK SA", ticker: "CABK" },
  { name: "CHENIERE ENERGY INC", ticker: "LNG" },
  { name: "DEUTSCHE POST AG", ticker: "DHL" },
  { name: "VISTRA CORP", ticker: "VST" },
  { name: "PANASONIC HOLDINGS CORP", ticker: "6752" },
  { name: "STRATEGY INC CLASS A", ticker: "MSTR" },
  { name: "ARTHUR J GALLAGHER", ticker: "AJG" },
  { name: "CARRIER GLOBAL CORP", ticker: "CARR" },
  { name: "AUTODESK INC", ticker: "ADSK" },
  { name: "AMERIPRISE FINANCE INC", ticker: "AMP" },
  { name: "STANDARD CHARTERED PLC", ticker: "STAN" },
  { name: "HOLCIM LTD AG", ticker: "HOLN" },
  { name: "CARVANA CLASS A", ticker: "CVNA" },
  { name: "COMPASS GROUP PLC", ticker: "CPG" },
  { name: "EBAY INC", ticker: "EBAY" },
  { name: "NIKE INC CLASS B", ticker: "NKE" },
  { name: "ELECTRONIC ARTS INC", ticker: "EA" },
  { name: "ENTERGY CORP", ticker: "ETR" },
  { name: "FASTENAL", ticker: "FAST" },
  { name: "ARGENX", ticker: "ARGX" },
  { name: "PRYSMIAN", ticker: "PRY" },
  { name: "JAPAN TOBACCO INC", ticker: "2914" },
  { name: "E.ON N", ticker: "EOAN" },
  { name: "DSV", ticker: "DSV" },
  { name: "NINTENDO LTD", ticker: "7974" },
  { name: "MARUBENI CORP", ticker: "8002" },
  { name: "PUBLIC STORAGE REIT", ticker: "PSA" },
  { name: "RIO TINTO LTD", ticker: "RIO" },
  { name: "SUMITOMO CORP", ticker: "8053" },
  { name: "SNOWFLAKE INC", ticker: "SNOW" },
  { name: "CENCORA INC", ticker: "COR" },
  { name: "ASM INTERNATIONAL NV", ticker: "ASM" },
  { name: "FERGUSON ENTERPRISES INC", ticker: "FERG" },
  { name: "SWISS RE AG", ticker: "SREN" },
  { name: "COINBASE GLOBAL INC CLASS A", ticker: "COIN" },
  { name: "DANONE SA", ticker: "BN" },
  { name: "ON SEMICONDUCTOR CORP", ticker: "ON" },
  { name: "KDDI CORP", ticker: "9433" },
  { name: "FORD MOTOR CO", ticker: "F" },
  { name: "HONG KONG EXCHANGES AND CLEARING L", ticker: "388" },
  { name: "DAIKIN INDUSTRIES LTD", ticker: "6367" },
  { name: "GOODMAN GROUP UNITS", ticker: "GMG" },
  { name: "XCEL ENERGY INC", ticker: "XEL" },
  { name: "LONZA GROUP AG", ticker: "LONN" },
  { name: "WESTINGHOUSE AIR BRAKE TECHNOLOGIE", ticker: "WAB" },
  { name: "BANK LEUMI LE ISRAEL", ticker: "LUMI" },
  { name: "LEGRAND SA", ticker: "LR" },
  { name: "EDWARDS LIFESCIENCES CORP", ticker: "EW" },
  { name: "EXELON CORP", ticker: "EXC" },
  { name: "CBRE GROUP INC CLASS A", ticker: "CBRE" },
  { name: "DIAGEO PLC", ticker: "DGE" },
  { name: "FRANCO NEVADA CORP", ticker: "FNV" },
  { name: "DISCO CORP", ticker: "6146" },
  { name: "MSCI INC", ticker: "MSCI" },
  { name: "METLIFE INC", ticker: "MET" },
  { name: "CELESTICA INC", ticker: "CLS" },
  { name: "FIFTH THIRD BANCORP", ticker: "FITB" },
  { name: "SOFTBANK CORP", ticker: "9434" },
  { name: "MERCEDES-BENZ GROUP N AG", ticker: "MBG" },
  { name: "CARDINAL HEALTH INC", ticker: "CAH" },
  { name: "REPUBLIC SERVICES INC", ticker: "RSG" },
  { name: "IDEXX LABORATORIES INC", ticker: "IDXX" },
  { name: "ALIMENTATION COUCHE TARD INC", ticker: "ATD" },
  { name: "UNITED OVERSEAS BANK LTD", ticker: "U11" },
  { name: "SANDVIK", ticker: "SAND" },
  { name: "FANUC CORP", ticker: "6954" },
  { name: "WOODSIDE ENERGY GROUP LTD", ticker: "WDS" },
  { name: "CHIPOTLE MEXICAN GRILL INC", ticker: "CMG" },
  { name: "ORIX CORP", ticker: "8591" },
  { name: "STATE STREET CORP", ticker: "STT" },
  { name: "BAYER AG", ticker: "BAYN" },
  { name: "AMERICAN INTERNATIONAL GROUP INC", ticker: "AIG" },
  { name: "EMCOR GROUP INC", ticker: "EME" },
  { name: "TEVA PHARMACEUTICAL INDUSTRIES ADR", ticker: "TEVA" },
  { name: "RWE AG", ticker: "RWE" },
  { name: "RENESAS ELECTRONICS CORP", ticker: "6723" },
  { name: "YUM BRANDS INC", ticker: "YUM" },
  { name: "TESCO PLC", ticker: "TSCO" },
  { name: "FERRARI NV", ticker: "RACE" },
  { name: "SSE PLC", ticker: "SSE" },
  { name: "PAYPAL HOLDINGS INC", ticker: "PYPL" },
  { name: "COMPAGNIE DE SAINT GOBAIN SA", ticker: "SGO" },
  { name: "PRUDENTIAL PLC", ticker: "PRU" },
  { name: "NASDAQ INC", ticker: "NDAQ" },
  { name: "TAKE TWO INTERACTIVE SOFTWARE INC", ticker: "TTWO" },
  { name: "BLOCK INC CLASS A", ticker: "XYZ" },
  { name: "BECTON DICKINSON", ticker: "BDX" },
  { name: "RECKITT BENCKISER GROUP PLC", ticker: "RKT" },
  { name: "KONINKLIJKE AHOLD DELHAIZE NV", ticker: "AD" },
  { name: "D R HORTON INC", ticker: "DHI" },
  { name: "CENOVUS ENERGY", ticker: "CVE" },
  { name: "HALEON PLC", ticker: "HLN" },
  { name: "ORANGE SA", ticker: "ORA" },
  { name: "ASSICURAZIONI GENERALI", ticker: "G" },
  { name: "NEBIUS NV CLASS A", ticker: "NBIS" },
  { name: "JABIL INC", ticker: "JBL" },
  { name: "WASTE CONNECTIONS INC", ticker: "WCN" },
  { name: "GARMIN LTD", ticker: "GRMN" },
  { name: "TDK CORP", ticker: "6762" },
  { name: "GALDERMA GROUP N AG", ticker: "GALD" },
  { name: "KROGER", ticker: "KR" },
  { name: "CROWN CASTLE INC", ticker: "CCI" },
  { name: "HEWLETT PACKARD ENTERPRISE", ticker: "HPE" },
  { name: "OCCIDENTAL PETROLEUM CORP", ticker: "OXY" },
  { name: "SUN LIFE FINANCIAL INC", ticker: "SLF" },
  { name: "VENTAS REIT INC", ticker: "VTR" },
  { name: "STMICROELECTRONICS NV", ticker: "STMPA" },
  { name: "PUBLIC SERVICE ENTERPRISE GROUP IN", ticker: "PEG" },
  { name: "KINROSS GOLD CORP", ticker: "K" },
  { name: "IRON MOUNTAIN INC", ticker: "IRM" },
  { name: "ARCHER DANIELS MIDLAND", ticker: "ADM" },
  { name: "HARTFORD INSURANCE GROUP INC", ticker: "HIG" },
  { name: "OLD DOMINION FREIGHT LINE INC", ticker: "ODFL" },
  { name: "ERSTE GROUP BANK AG", ticker: "EBS" },
  { name: "CBOE GLOBAL MARKETS INC", ticker: "CBOE" },
  { name: "KOMATSU LTD", ticker: "6301" },
  { name: "ERICSSON B", ticker: "ERIC B" },
  { name: "VULCAN MATERIALS", ticker: "VMC" },
  { name: "CONSOLIDATED EDISON INC", ticker: "ED" },
  { name: "DIAMONDBACK ENERGY INC", ticker: "FANG" },
  { name: "INTERACTIVE BROKERS GROUP INC CLAS", ticker: "IBKR" },
  { name: "KEURIG DR PEPPER INC", ticker: "KDP" },
  { name: "ASSA ABLOY B", ticker: "ASSA B" },
  { name: "CONSTELLATION SOFTWARE INC", ticker: "CSU" },
  { name: "STEEL DYNAMICS INC", ticker: "STLD" },
  { name: "ALNYLAM PHARMACEUTICALS INC", ticker: "ALNY" },
  { name: "FERROVIAL NV", ticker: "FER" },
  { name: "HALLIBURTON", ticker: "HAL" },
  { name: "WEC ENERGY GROUP INC", ticker: "WEC" },
  { name: "FUJITSU LTD", ticker: "6702" },
  { name: "CSL LTD", ticker: "CSL" },
  { name: "DAIICHI LIFE GROUP INC", ticker: "8750" },
  { name: "PG&E CORP", ticker: "PCG" },
  { name: "SYSCO CORP", ticker: "SYY" },
  { name: "EQT CORP", ticker: "EQT" },
  { name: "SANDOZ GROUP AG", ticker: "SDZ" },
  { name: "NUTRIEN LTD", ticker: "NTR" },
  { name: "ROPER TECHNOLOGIES INC", ticker: "ROP" },
  { name: "ZOETIS INC CLASS A", ticker: "ZTS" },
  { name: "DOLLARAMA INC", ticker: "DOL" },
  { name: "PRUDENTIAL FINANCIAL INC", ticker: "PRU" },
  { name: "JAPAN POST BANK LTD", ticker: "7182" },
  { name: "MARTIN MARIETTA MATERIALS INC", ticker: "MLM" },
  { name: "EXPERIAN PLC", ticker: "EXPN" },
  { name: "SEA ADS REPRESENTING LTD CLASS A", ticker: "SE" },
  { name: "TRANSURBAN GROUP STAPLED UNITS", ticker: "TCL" },
  { name: "KENVUE INC", ticker: "KVUE" },
  { name: "WATERS CORP", ticker: "WAT" },
  { name: "SOMPO HOLDINGS INC", ticker: "8630" },
  { name: "HONDA MOTOR LTD", ticker: "7267" },
  { name: "ARCH CAPITAL GROUP LTD", ticker: "ACGL" },
  { name: "CREDO TECHNOLOGY GROUP HOLDING LTD", ticker: "CRDO" },
  { name: "3I GROUP PLC", ticker: "III" },
  { name: "POWER CORPORATION OF CANADA", ticker: "POW" },
  { name: "HUMANA INC", ticker: "HUM" },
  { name: "MS&AD INSURANCE GROUP HOLDINGS INC", ticker: "8725" },
  { name: "COMMERZBANK AG", ticker: "CBK" },
  { name: "CHUGAI PHARMACEUTICAL LTD", ticker: "4519" },
  { name: "M&T BANK CORP", ticker: "MTB" },
  { name: "UCB SA", ticker: "UCB" },
  { name: "CASEYS GENERAL STORES INC", ticker: "CASY" },
  { name: "GIVAUDAN SA", ticker: "GIVN" },
  { name: "HUNTINGTON BANCSHARES INC", ticker: "HBAN" },
  { name: "TWILIO INC CLASS A", ticker: "TWLO" },
  { name: "EQUINOR", ticker: "EQNR" },
  { name: "INTACT FINANCIAL CORP", ticker: "IFC" },
  { name: "KBC GROEP", ticker: "KBC" },
  { name: "DANSKE BANK", ticker: "DANSKE" },
  { name: "FAIRFAX FINANCIAL HOLDINGS SUB VOT", ticker: "FFH" },
  { name: "QNITY ELECTRONICS INC", ticker: "Q" },
  { name: "TOYOTA TSUSHO CORP", ticker: "8015" },
  { name: "AGILENT TECHNOLOGIES INC", ticker: "A" },
  { name: "KIMBERLY CLARK CORP", ticker: "KMB" },
  { name: "BANK HAPOALIM BM", ticker: "POLI" },
  { name: "SUN HUNG KAI PROPERTIES LTD", ticker: "16" },
  { name: "VODAFONE GROUP PLC", ticker: "VOD" },
  { name: "NTT INC", ticker: "9432" },
  { name: "MITSUI FUDOSAN LTD", ticker: "8801" },
  { name: "VESTAS WIND SYSTEMS", ticker: "VWS" },
  { name: "OTSUKA HOLDINGS LTD", ticker: "4578" },
  { name: "EXTRA SPACE STORAGE REIT INC", ticker: "EXR" },
  { name: "REPSOL SA", ticker: "REP" },
  { name: "NEC CORP", ticker: "6701" },
  { name: "COPART INC", ticker: "CPRT" },
  { name: "DOVER CORP", ticker: "DOV" },
  { name: "AJINOMOTO INC", ticker: "2802" },
  { name: "SWISS LIFE HOLDING AG", ticker: "SLHN" },
  { name: "NORTHERN TRUST CORP", ticker: "NTRS" },
  { name: "PAYCHEX INC", ticker: "PAYX" },
  { name: "INGERSOLL RAND INC", ticker: "IR" },
  { name: "FISERV INC", ticker: "FISV" },
  { name: "RAYMOND JAMES INC", ticker: "RJF" },
  { name: "DAIICHI SANKYO LTD", ticker: "4568" },
  { name: "ALCON AG", ticker: "ALC" },
  { name: "VICI PPTYS INC", ticker: "VICI" },
  { name: "SUNBELT RENTALS HOLDINGS INC", ticker: "SUNB" },
  { name: "AMEREN CORP", ticker: "AEE" },
  { name: "TELEDYNE TECHNOLOGIES INC", ticker: "TDY" },
  { name: "SKANDINAVISKA ENSKILDA BANKEN", ticker: "SEB A" },
  { name: "SWEDBANK", ticker: "SWED A" },
  { name: "IQVIA HOLDINGS INC", ticker: "IQV" },
  { name: "SINGAPORE TELECOMMUNICATIONS LTD", ticker: "Z74" },
  { name: "BIOGEN INC", ticker: "BIIB" },
  { name: "HEIDELBERG MATERIALS AG", ticker: "HEI" },
  { name: "FORTIS INC", ticker: "FTS" },
  { name: "OTIS WORLDWIDE CORP", ticker: "OTIS" },
  { name: "RESMED INC", ticker: "RMD" },
  { name: "TECK RESOURCES SUBORDINATE VOTING", ticker: "TECK.B" },
  { name: "FTAI AVIATION LTD", ticker: "FTAI" },
  { name: "DTE ENERGY", ticker: "DTE" },
  { name: "ASTELLAS PHARMA INC", ticker: "4503" },
  { name: "WOOLWORTHS GROUP LTD", ticker: "WOW" },
  { name: "AXON ENTERPRISE INC", ticker: "AXON" },
  { name: "IMPERIAL BRANDS PLC", ticker: "IMB" },
  { name: "NRG ENERGY INC", ticker: "NRG" },
  { name: "ASTERA LABS INC", ticker: "ALAB" },
  { name: "ATMOS ENERGY CORP", ticker: "ATO" },
  { name: "ADIDAS N AG", ticker: "ADS" },
  { name: "ACS ACTIVIDADES DE CONSTRUCCION Y", ticker: "ACS" },
  { name: "MITSUBISHI ESTATE CO LTD", ticker: "8802" },
  { name: "GE HEALTHCARE TECHNOLOGIES INC", ticker: "GEHC" },
  { name: "SIKA AG", ticker: "SIKA" },
  { name: "LOBLAW COMPANIES LTD", ticker: "L" },
  { name: "TAPESTRY INC", ticker: "TPR" },
  { name: "ZOOM COMMUNICATIONS INC CLASS A", ticker: "ZM" },
  { name: "FAIR ISAAC CORP", ticker: "FICO" },
  { name: "ADYEN NV", ticker: "ADYEN" },
  { name: "EXPEDIA GROUP INC", ticker: "EXPE" },
  { name: "CENTENE CORP", ticker: "CNC" },
  { name: "EDISON INTERNATIONAL", ticker: "EIX" },
  { name: "TECHTRONIC INDUSTRIES LTD", ticker: "669" },
  { name: "HERSHEY FOODS", ticker: "HSY" },
  { name: "VEOLIA ENVIRON. SA", ticker: "VIE" },
  { name: "CENTERPOINT ENERGY INC", ticker: "CNP" },
  { name: "XYLEM INC", ticker: "XYL" },
  { name: "CITIZENS FINANCIAL GROUP INC", ticker: "CFG" },
  { name: "COREWEAVE INC CLASS A", ticker: "CRWV" },
  { name: "RESONA HOLDINGS INC", ticker: "8308" },
  { name: "SMC (JAPAN) CORP", ticker: "6273" },
  { name: "PPL CORP", ticker: "PPL" },
  { name: "EVERPURE INC CLASS A", ticker: "P" },
  { name: "ATLAS COPCO CLASS B", ticker: "ATCO B" },
  { name: "ARES MANAGEMENT CORP CLASS A", ticker: "ARES" },
  { name: "AMADEUS IT GROUP SA", ticker: "AMS" },
  { name: "CURTISS WRIGHT CORP", ticker: "CW" },
  { name: "AVALONBAY COMMUNITIES REIT INC", ticker: "AVB" },
  { name: "AMRIZE AG", ticker: "AMRZ" },
  { name: "BMW AG", ticker: "BMW" },
  { name: "ARCELORMITTAL SA", ticker: "MT" },
  { name: "DOW INC", ticker: "DOW" },
  { name: "FORTESCUE LTD", ticker: "FMG" },
  { name: "DNB BANK", ticker: "DNB" },
  { name: "HUBBELL INC", ticker: "HUBB" },
  { name: "PAN AMERICAN SILVER CORP", ticker: "PAAS" },
  { name: "SYNCHRONY FINANCIAL", ticker: "SYF" },
  { name: "PEMBINA PIPELINE CORP", ticker: "PPL" },
  { name: "CARNIVAL CORP", ticker: "CCL" },
  { name: "WORKDAY INC CLASS A", ticker: "WDAY" },
  { name: "THALES SA", ticker: "HO" },
  { name: "SEVEN & I HOLDINGS LTD", ticker: "3382" },
  { name: "LIVE NATION ENTERTAINMENT INC", ticker: "LYV" },
  { name: "IBIDEN LTD", ticker: "4062" },
  { name: "SAMPO CLASS A", ticker: "SAMPO" },
  { name: "PARTNERS GROUP HOLDING AG", ticker: "PGHN" },
  { name: "AVIVA PLC", ticker: "AV." },
  { name: "MICHELIN", ticker: "ML" },
  { name: "UNIVERSAL MUSIC GROUP NV", ticker: "UMG" },
  { name: "FIRSTENERGY CORP", ticker: "FE" },
  { name: "INTERCONTINENTAL HOTELS GROUP PLC", ticker: "IHG" },
  { name: "KYOCERA CORP", ticker: "6971" },
  { name: "NATERA INC", ticker: "NTRA" },
  { name: "TOWER SEMICONDUCTOR LTD", ticker: "TSEM" },
  { name: "ENEOS HOLDINGS INC", ticker: "5020" },
  { name: "UNITED THERAPEUTICS CORP", ticker: "UTHR" },
  { name: "REGIONS FINANCIAL CORP", ticker: "RF" },
  { name: "RESTAURANTS BRANDS INTERNATIONAL I", ticker: "QSR" },
  { name: "ULTA BEAUTY INC", ticker: "ULTA" },
  { name: "AERCAP HOLDINGS NV", ticker: "AER" },
  { name: "PPG INDUSTRIES INC", ticker: "PPG" },
  { name: "CK HUTCHISON HOLDINGS LTD", ticker: "1" },
  { name: "HELVETIA BALOISE HOLDING N AG", ticker: "HBAN" },
  { name: "COGNIZANT TECHNOLOGY SOLUTIONS COR", ticker: "CTSH" },
  { name: "CINCINNATI FINANCIAL CORP", ticker: "CINF" },
  { name: "QBE INSURANCE GROUP LTD", ticker: "QBE" },
  { name: "WILLIS TOWERS WATSON PLC", ticker: "WTW" },
  { name: "FIRST SOLAR INC", ticker: "FSLR" },
  { name: "NOMURA HOLDINGS INC", ticker: "8604" },
  { name: "EVERSOURCE ENERGY", ticker: "ES" },
  { name: "MONGODB INC CLASS A", ticker: "MDB" },
  { name: "OMNICOM GROUP INC", ticker: "OMC" },
  { name: "LEONARDO FINMECCANICA SPA", ticker: "LDO" },
  { name: "WEST PHARMACEUTICAL SERVICES INC", ticker: "WST" },
  { name: "SBA COMMUNICATIONS REIT CORP CLASS", ticker: "SBAC" },
  { name: "VERISIGN INC", ticker: "VRSN" },
  { name: "VEEVA SYSTEMS INC CLASS A", ticker: "VEEV" },
  { name: "MARKEL GROUP INC", ticker: "MKL" },
  { name: "FUJIFILM HOLDINGS CORP", ticker: "4901" },
  { name: "BOC HONG KONG HOLDINGS LTD", ticker: "2388" },
  { name: "ROBLOX CORP CLASS A", ticker: "RBLX" },
  { name: "AMERICAN WATER WORKS INC", ticker: "AWK" },
  { name: "CREDIT AGRICOLE SA", ticker: "ACA" },
  { name: "DOLLAR GENERAL CORP", ticker: "DG" },
  { name: "ENTEGRIS INC", ticker: "ENTG" },
  { name: "RYANAIR HOLDINGS PLC", ticker: "RYA" },
  { name: "VERISK ANALYTICS INC", ticker: "VRSK" },
  { name: "METTLER TOLEDO INC", ticker: "MTD" },
  { name: "BPER BANCA", ticker: "BPE" },
  { name: "CANON INC", ticker: "7751" },
  { name: "NETAPP INC", ticker: "NTAP" },
  { name: "VAT GROUP AG", ticker: "VACN" },
  { name: "FIDELITY NATIONAL INFORMATION SERV", ticker: "FIS" },
  { name: "TEXAS PACIFIC LAND CORP", ticker: "TPL" },
  { name: "PULTEGROUP INC", ticker: "PHM" },
  { name: "DENSO CORP", ticker: "6902" },
  { name: "LPL FINANCIAL HOLDINGS INC", ticker: "LPLA" },
  { name: "DEXCOM INC", ticker: "DXCM" },
  { name: "EQUITY RESIDENTIAL REIT", ticker: "EQR" },
  { name: "AEON LTD", ticker: "8267" },
  { name: "CORPAY INC", ticker: "CPAY" },
  { name: "GEBERIT AG", ticker: "GEBN" },
  { name: "BE SEMICONDUCTOR INDUSTRIES NV", ticker: "BESI" },
  { name: "PRINCIPAL FINANCIAL GROUP INC", ticker: "PFG" },
  { name: "INSMED INC", ticker: "INSM" },
  { name: "IMPERIAL OIL LTD", ticker: "IMO" },
  { name: "ELBIT SYSTEMS LTD", ticker: "ESLT" },
  { name: "NN GROUP NV", ticker: "NN" },
  { name: "INPEX CORP", ticker: "1605" },
  { name: "QUEST DIAGNOSTICS INC", ticker: "DGX" },
  { name: "HALMA PLC", ticker: "HLMA" },
  { name: "DARDEN RESTAURANTS INC", ticker: "DRI" },
  { name: "DAIMLER TRUCK HOLDING E AG", ticker: "DTG" },
  { name: "NISOURCE INC", ticker: "NI" },
  { name: "BANCA MONTE DEI PASCHI DI SIENA SP", ticker: "BMPS" },
  { name: "BRAMBLES LTD", ticker: "BXB" },
  { name: "NEXT PLC", ticker: "NXT" },
  { name: "ILLUMINA INC", ticker: "ILMN" },
  { name: "COLES GROUP LTD", ticker: "COL" },
  { name: "BRIDGESTONE CORP", ticker: "5108" },
  { name: "FORTIVE CORP", ticker: "FTV" },
  { name: "COCA COLA EUROPACIFIC PARTNERS PLC", ticker: "CCEP" },
  { name: "CHURCH AND DWIGHT INC", ticker: "CHD" },
  { name: "BT GROUP PLC", ticker: "BT.A" },
  { name: "JAPAN POST HOLDINGS LTD", ticker: "6178" },
  { name: "T ROWE PRICE GROUP INC", ticker: "TROW" },
  { name: "ROYALTY PHARMA PLC CLASS A", ticker: "RPRX" },
  { name: "VERALTO CORP", ticker: "VLTO" },
  { name: "SUMITOMO MITSUI TRUST GROUP INC", ticker: "8309" },
  { name: "WILLIAMS SONOMA INC", ticker: "WSM" },
  { name: "REVOLUTION MEDICINES INC", ticker: "RVMD" },
  { name: "DUPONT DE NEMOURS INC", ticker: "DD" },
  { name: "KONINKLIJKE PHILIPS NV", ticker: "PHIA" },
  { name: "KERING SA", ticker: "KER" },
  { name: "KRAFT HEINZ", ticker: "KHC" },
  { name: "PUBLICIS GROUPE SA", ticker: "PUB" },
  { name: "F5 INC", ticker: "FFIV" },
  { name: "CONSTELLATION BRANDS INC CLASS A", ticker: "STZ" },
  { name: "NOVOZYMES B", ticker: "NSIS B" },
  { name: "LABCORP HOLDINGS INC", ticker: "LH" },
  { name: "KONINKLIJKE KPN NV", ticker: "KPN" },
  { name: "HEINEKEN NV", ticker: "HEIA" },
  { name: "CMS ENERGY CORP", ticker: "CMS" },
  { name: "WARTSILA", ticker: "WRT1V" },
  { name: "STERIS", ticker: "STE" },
  { name: "EXPEDITORS INTERNATIONAL OF WASHIN", ticker: "EXPD" },
  { name: "RELIANCE STEEL & ALUMINUM", ticker: "RS" },
  { name: "KONE", ticker: "KNEBV" },
  { name: "FRESENIUS SE AND CO KGAA", ticker: "FRE" },
  { name: "INTERNATIONAL FLAVORS & FRAGRANCES", ticker: "IFF" },
  { name: "BANCO DE SABADELL SA", ticker: "SAB" },
  { name: "COEUR MINING INC", ticker: "CDE" },
  { name: "EQUIFAX INC", ticker: "EFX" },
  { name: "ABN AMRO BANK NV", ticker: "ABN" },
  { name: "EAST JAPAN RAILWAY", ticker: "9020" },
  { name: "SVENSKA HANDELSBANKEN-A SHS", ticker: "SHB A" },
  { name: "LASERTEC CORP", ticker: "6920" },
  { name: "CF INDUSTRIES HOLDINGS INC", ticker: "CF" },
  { name: "HEXAGON CLASS B", ticker: "HEXA B" },
  { name: "AIB GROUP PLC", ticker: "A5G" },
  { name: "EPIROC CLASS A", ticker: "EPI A" },
  { name: "NORTHERN STAR RESOURCES LTD", ticker: "NST" },
  { name: "VOLKSWAGEN NON-VOTING PREF AG", ticker: "VOW3" },
  { name: "BANK OF IRELAND GROUP PLC", ticker: "BIRG" },
  { name: "BROOKFIELD ASSET MANAGEMENT VOTING", ticker: "BAM" },
  { name: "PACKAGING CORP OF AMERICA", ticker: "PKG" },
  { name: "SMURFIT WESTROCK PLC", ticker: "SW" },
  { name: "JX ADVANCED METALS CORP", ticker: "5016" },
  { name: "ANTOFAGASTA PLC", ticker: "ANTO" },
  { name: "KEYCORP", ticker: "KEY" },
  { name: "EXPAND ENERGY CORP", ticker: "EXE" },
  { name: "HP INC", ticker: "HPQ" },
  { name: "LIBERTY MEDIA FORMULA ONE SERIES C", ticker: "FWONK" },
  { name: "ESTEE LAUDER INC CLASS A", ticker: "EL" },
  { name: "VONOVIA SE", ticker: "VNA" },
  { name: "SNAP ON INC", ticker: "SNA" },
  { name: "GENERAL MILLS INC", ticker: "GIS" },
  { name: "SWISSCOM AG", ticker: "SCMN" },
  { name: "SUZUKI MOTOR CORP", ticker: "7269" },
  { name: "TYSON FOODS INC CLASS A", ticker: "TSN" },
  { name: "AENA SME SA", ticker: "AENA" },
  { name: "EVERGY INC", ticker: "EVRG" },
  { name: "CAPGEMINI", ticker: "CAP" },
  { name: "WSP GLOBAL INC", ticker: "WSP" },
  { name: "ARISTOCRAT LEISURE LTD", ticker: "ALL" },
  { name: "BURLINGTON STORES INC", ticker: "BURL" },
  { name: "EVOLUTION MINING LTD", ticker: "EVN" },
  { name: "AST SPACEMOBILE INC CLASS A", ticker: "ASTS" },
  { name: "ECHOSTAR CORP CLASS A", ticker: "SATS" },
  { name: "FIRST QUANTUM MINERALS LTD", ticker: "FM" },
  { name: "AMCOR PLC", ticker: "AMCR" },
  { name: "LOEWS CORP", ticker: "L" },
  { name: "RB GLOBAL INC", ticker: "RBA" },
  { name: "LENNAR A CORP CLASS A", ticker: "LEN" },
  { name: "CH ROBINSON WORLDWIDE INC", ticker: "CHRW" },
  { name: "ALAMOS GOLD INC CLASS A", ticker: "AGI" },
  { name: "CLP HOLDINGS LTD", ticker: "2" },
  { name: "LUNDIN MINING CORP", ticker: "LUN" },
  { name: "TERUMO CORP", ticker: "4543" },
  { name: "ALLIANT ENERGY CORP", ticker: "LNT" },
  { name: "PHOENIX FINANCIAL LTD", ticker: "PHOE" },
  { name: "LEGAL AND GENERAL GROUP PLC", ticker: "LGEN" },
  { name: "JB HUNT TRANSPORT SERVICES INC", ticker: "JBHT" },
  { name: "FIRST CITIZENS BANCSHARES INC CLAS", ticker: "FCNCA" },
  { name: "SANTOS LTD", ticker: "STO" },
  { name: "JULIUS BAER GRUPPE AG", ticker: "BAER" },
  { name: "IREN LTD", ticker: "IREN" },
  { name: "LYONDELLBASELL INDUSTRIES NV CLASS", ticker: "LYB" },
  { name: "CENTRAL JAPAN RAILWAY", ticker: "9022" },
  { name: "SUMITOMO REALTY & DEVELOPMENT LTD", ticker: "8830" },
  { name: "SOFI TECHNOLOGIES INC", ticker: "SOFI" },
  { name: "AFFIRM HOLDINGS INC CLASS A", ticker: "AFRM" },
  { name: "INVITATION HOMES INC", ticker: "INVH" },
  { name: "TELEFONICA SA", ticker: "TEF" },
  { name: "BUNGE GLOBAL SA", ticker: "BG" },
  { name: "BANCO BPM", ticker: "BAMI" },
  { name: "LOGITECH INTERNATIONAL SA", ticker: "LOGN" },
  { name: "SUPER MICRO COMPUTER INC", ticker: "SMCI" },
  { name: "BOMBARDIER INC CLASS B", ticker: "BBD.B" },
  { name: "PTC INC", ticker: "PTC" },
  { name: "EBARA CORP", ticker: "6361" },
  { name: "SAAB CLASS B", ticker: "SAAB B" },
  { name: "CELLNEX TELECOM", ticker: "CLNX" },
  { name: "MTU AERO ENGINES HOLDING AG", ticker: "MTX" },
  { name: "GENMAB", ticker: "GMAB" },
  { name: "DOLLAR TREE INC", ticker: "DLTR" },
  { name: "TEXTRON INC", ticker: "TXT" },
  { name: "ALFA LAVAL", ticker: "ALFA" },
  { name: "IONQ INC", ticker: "IONQ" },
  { name: "MERCK", ticker: "MRK" },
  { name: "DAIFUKU LTD", ticker: "6383" },
  { name: "KAJIMA CORP", ticker: "1812" },
  { name: "WOLTERS KLUWER NV", ticker: "WKL" },
  { name: "SHIONOGI LTD", ticker: "4507" },
  { name: "MAGNA INTERNATIONAL INC", ticker: "MG" },
  { name: "WEYERHAEUSER REIT", ticker: "WY" },
  { name: "ASICS CORP", ticker: "7936" },
  { name: "FINECOBANK BANCA FINECO", ticker: "FBK" },
  { name: "SGS SA", ticker: "SGSN" },
  { name: "BROADRIDGE FINANCIAL SOLUTIONS INC", ticker: "BR" },
  { name: "EQT", ticker: "EQT" },
  { name: "REDDIT INC CLASS A", ticker: "RDDT" },
  { name: "WR BERKLEY CORP", ticker: "WRB" },
  { name: "INCYTE CORP", ticker: "INCY" },
  { name: "IHI CORP", ticker: "7013" },
  { name: "BROWN & BROWN INC", ticker: "BRO" },
  { name: "BOLIDEN", ticker: "BOL" },
  { name: "ESSEX PROPERTY TRUST REIT INC", ticker: "ESS" },
  { name: "KAO CORP", ticker: "4452" },
  { name: "UPM-KYMMENE", ticker: "UPM" },
  { name: "KIMCO REALTY REIT CORP", ticker: "KIM" },
  { name: "TAISEI CORP", ticker: "1801" },
  { name: "TRACTOR SUPPLY", ticker: "TSCO" },
  { name: "KUBOTA CORP", ticker: "6326" },
  { name: "SUN COMMUNITIES REIT INC", ticker: "SUI" },
  { name: "INTERNATIONAL PAPER", ticker: "IP" },
  { name: "GLOBAL PAYMENTS INC", ticker: "GPN" },
  { name: "LENNOX INTERNATIONAL INC", ticker: "LII" },
  { name: "LAS VEGAS SANDS CORP", ticker: "LVS" },
  { name: "CARLISLE COMPANIES INC", ticker: "CSL" },
  { name: "NORSK HYDRO", ticker: "NHY" },
  { name: "TOURMALINE OIL CORP", ticker: "TOU" },
  { name: "IDEX CORP", ticker: "IEX" },
  { name: "EDP ENERGIAS DE PORTUGAL SA", ticker: "EDP" },
  { name: "NIPPON STEEL CORP", ticker: "5401" },
  { name: "GREAT WEST LIFECO INC", ticker: "GWO" },
  { name: "HANNOVER RUECK", ticker: "HNR1" },
  { name: "FLUTTER ENTERTAINMENT PLC", ticker: "FLUT" },
  { name: "DAIWA SECURITIES GROUP INC", ticker: "8601" },
  { name: "NORDSON CORP", ticker: "NDSN" },
  { name: "W. P. CAREY REIT INC", ticker: "WPC" },
  { name: "DAIWA HOUSE INDUSTRY LTD", ticker: "1925" },
  { name: "ZIMMER BIOMET HOLDINGS INC", ticker: "ZBH" },
  { name: "TERNA RETE ELETTRICA NAZIONALE", ticker: "TRN" },
  { name: "SCHINDLER HOLDING PAR AG", ticker: "SCHP" },
  { name: "HEICO CORP CLASS A", ticker: "HEIA" },
  { name: "RENTOKIL INITIAL PLC", ticker: "RTO" },
  { name: "SS AND C TECHNOLOGIES HOLDINGS INC", ticker: "SSNC" },
  { name: "BALL CORP", ticker: "BALL" },
  { name: "ESSITY CLASS B", ticker: "ESSITY B" },
  { name: "LEIDOS HOLDINGS INC", ticker: "LDOS" },
  { name: "NOVA LTD", ticker: "NVMI" },
  { name: "NIPPON YUSEN", ticker: "9101" },
  { name: "DASSAULT SYSTEMES", ticker: "DSY" },
  { name: "ROLLINS INC", ticker: "ROL" },
  { name: "EMERA INC", ticker: "EMA" },
  { name: "INFORMA PLC", ticker: "INF" },
  { name: "TELSTRA GROUP LTD", ticker: "TLS" },
  { name: "NIDEC CORP", ticker: "6594" },
  { name: "DECKERS OUTDOOR CORP", ticker: "DECK" },
  { name: "JACOBS SOLUTIONS INC", ticker: "J" },
  { name: "ZSCALER INC", ticker: "ZS" },
  { name: "WATSCO INC", ticker: "WSO" },
  { name: "ORIGIN ENERGY LTD", ticker: "ORG" },
  { name: "STELLANTIS NV", ticker: "STLAM" },
  { name: "SINGAPORE EXCHANGE LTD", ticker: "S68" },
  { name: "PINNACLE FINANCIAL PARTNERS INC", ticker: "PNFP" },
  { name: "NITTO DENKO CORP", ticker: "6988" },
  { name: "MID AMERICA APARTMENT COMMUNITIES", ticker: "MAA" },
  { name: "ORSTED A/S", ticker: "ORSTED" },
  { name: "PERNOD RICARD SA", ticker: "RI" },
  { name: "SWISS PRIME SITE AG", ticker: "SPSN" },
  { name: "SUMITOMO METAL MINING LTD", ticker: "5713" },
  { name: "MASCO CORP", ticker: "MAS" },
  { name: "NEUROCRINE BIOSCIENCES INC", ticker: "NBIX" },
  { name: "SNAM", ticker: "SRG" },
  { name: "ATLASSIAN CORP CLASS A", ticker: "TEAM" },
  { name: "WHITECAP RESOURCES INC", ticker: "WCP" },
  { name: "OSAKA GAS LTD", ticker: "9532" },
  { name: "REGENCY CENTERS REIT CORP", ticker: "REG" },
  { name: "SCENTRE GROUP", ticker: "SCG" },
  { name: "ASAHI GROUP HOLDINGS LTD", ticker: "2502" },
  { name: "COCA COLA HBC AG", ticker: "CCH" },
  { name: "POSTE ITALIANE", ticker: "PST" },
  { name: "MITSUI OSK LINES LTD", ticker: "9104" },
  { name: "TRIMBLE INC", ticker: "TRMB" },
  { name: "NVR INC", ticker: "NVR" },
  { name: "SECOM LTD", ticker: "9735" },
  { name: "THOMSON REUTERS CORP", ticker: "TRI" },
  { name: "UNIBAIL RODAMCO WE STAPLED UNITS", ticker: "URW" },
  { name: "EVEREST GROUP LTD", ticker: "EG" },
  { name: "SBI HOLDINGS INC", ticker: "8473" },
  { name: "GENUINE PARTS", ticker: "GPC" },
  { name: "COSTAR GROUP INC", ticker: "CSGP" },
  { name: "LULULEMON ATHLETICA INC", ticker: "LULU" },
  { name: "FOX CORP CLASS A", ticker: "FOXA" },
  { name: "KERRY GROUP PLC", ticker: "KRZ" },
  { name: "ISRAEL DISCOUNT BANK LTD", ticker: "DSCT" },
  { name: "HEALTHPEAK PROPERTIES INC", ticker: "DOC" },
  { name: "CK ASSET HOLDINGS LTD", ticker: "1113" },
  { name: "JARDINE MATHESON HOLDINGS LTD", ticker: "J36" },
  { name: "ROCKET COMPANIES INC CLASS A", ticker: "RKT" },
  { name: "LINK REAL ESTATE INVESTMENT TRUST", ticker: "823" },
  { name: "HYDRO ONE LTD", ticker: "H" },
  { name: "ORIENTAL LAND LTD", ticker: "4661" },
  { name: "KANSAI ELECTRIC POWER INC", ticker: "9503" },
  { name: "KONGSBERG GRUPPEN", ticker: "KOG" },
  { name: "KEPPEL LTD", ticker: "BN4" },
  { name: "TELIA COMPANY", ticker: "TELIA" },
  { name: "MONCLER", ticker: "MONC" },
  { name: "CENTRICA PLC", ticker: "CNA" },
  { name: "BAWAG GROUP AG", ticker: "BG" },
  { name: "NESTE", ticker: "NESTE" },
  { name: "TYLER TECHNOLOGIES INC", ticker: "TYL" },
  { name: "SOUTH32 LTD", ticker: "S32" },
  { name: "CDW CORP", ticker: "CDW" },
  { name: "KINGSPAN GROUP PLC", ticker: "KRX" },
  { name: "EURONEXT NV", ticker: "ENX" },
  { name: "SINGAPORE TECHNOLOGIES ENGINEERING", ticker: "S63" },
  { name: "GAMING AND LEISURE PROPERTIES REIT", ticker: "GLPI" },
  { name: "POWER ASSETS HOLDINGS LTD", ticker: "6" },
  { name: "CGI INC CLASS A", ticker: "GIB.A" },
  { name: "OKTA INC CLASS A", ticker: "OKTA" },
  { name: "DICKS SPORTING INC", ticker: "DKS" },
  { name: "SIEMENS HEALTHINEERS AG", ticker: "SHL" },
  { name: "CHUBU ELECTRIC POWER INC", ticker: "9502" },
  { name: "TRADEWEB MARKETS INC CLASS A", ticker: "TW" },
  { name: "ENDEAVOUR MINING", ticker: "EDV" },
  { name: "ROCHE HOLDING AG", ticker: "RO" },
  { name: "ENDESA SA", ticker: "ELE" },
  { name: "LYNAS RARE EARTHS LTD", ticker: "LYC" },
  { name: "GEN DIGITAL INC", ticker: "GEN" },
  { name: "KIRIN HOLDINGS LTD", ticker: "2503" },
  { name: "METRO INC", ticker: "MRU" },
  { name: "TRANSUNION", ticker: "TRU" },
  { name: "AGEAS SA", ticker: "AGS" },
  { name: "DSM FIRMENICH AG", ticker: "DSFIR" },
  { name: "BOUYGUES SA", ticker: "EN" },
  { name: "ARC RESOURCES LTD", ticker: "ARX" },
  { name: "MIZRAHI TEFAHOT BANK LTD", ticker: "MZTF" },
  { name: "AVERY DENNISON CORP", ticker: "AVY" },
  { name: "BANDAI NAMCO HOLDINGS INC", ticker: "7832" },
  { name: "INSURANCE AUSTRALIA GROUP LTD", ticker: "IAG" },
  { name: "GRACO INC", ticker: "GGG" },
  { name: "ASAHI KASEI CORP", ticker: "3407" },
  { name: "TOKYO GAS LTD", ticker: "9531" },
  { name: "SUNCORP GROUP LTD", ticker: "SUN" },
  { name: "EIFFAGE SA", ticker: "FGR" },
  { name: "RPM INTERNATIONAL INC", ticker: "RPM" },
  { name: "IA FINANCIAL INC", ticker: "IAG" },
  { name: "TOPPAN HOLDINGS INC", ticker: "7911" },
  { name: "PINTEREST INC CLASS A", ticker: "PINS" },
  { name: "SEGRO REIT PLC", ticker: "SGRO" },
  { name: "PAN PACIFIC INTERNATIONAL HOLDINGS", ticker: "7532" },
  { name: "SEVERN TRENT PLC", ticker: "SVT" },
  { name: "CHARTER COMMUNICATIONS INC CLASS A", ticker: "CHTR" },
  { name: "CARLSBERG AS CL B", ticker: "CARL B" },
  { name: "HEICO CORP", ticker: "HEI" },
  { name: "KAWASAKI HEAVY INDUSTRIES LTD", ticker: "7012" },
  { name: "ANNALY CAPITAL MANAGEMENT REIT INC", ticker: "NLY" },
  { name: "HENKEL & KGAA PREF AG", ticker: "HEN3" },
  { name: "FUJI ELECTRIC LTD", ticker: "6504" },
  { name: "TOROMONT INDUSTRIES LTD", ticker: "TIH" },
  { name: "SMITHS GROUP PLC", ticker: "SMIN" },
  { name: "APTIV PLC", ticker: "APTV" },
  { name: "MCCORMICK & CO NON-VOTING INC", ticker: "MKC" },
  { name: "ROGERS COMMUNICATIONS NON-VOTING I", ticker: "RCI.B" },
  { name: "THE SAGE GROUP PLC", ticker: "SGE" },
  { name: "FIDELITY NATIONAL FINANCIAL INC", ticker: "FNF" },
  { name: "STRAUMANN HOLDING AG", ticker: "STMN" },
  { name: "GARTNER INC", ticker: "IT" },
  { name: "GODADDY INC CLASS A", ticker: "GDDY" },
  { name: "AEGON LTD", ticker: "AGN" },
  { name: "FISHER AND PAYKEL HEALTHCARE CORPO", ticker: "FPH" },
  { name: "DELTA AIR LINES INC", ticker: "DAL" },
  { name: "UNITED UTILITIES GROUP PLC", ticker: "UU." },
  { name: "ASR NEDERLAND NV", ticker: "ASRNL" },
  { name: "SMITH AND NEPHEW PLC", ticker: "SN." },
  { name: "BEST BUY INC", ticker: "BBY" },
  { name: "OLYMPUS CORP", ticker: "7733" },
  { name: "OBAYASHI CORP", ticker: "1802" },
  { name: "HONG KONG AND CHINA GAS LTD", ticker: "3" },
  { name: "CARLYLE GROUP INC", ticker: "CG" },
  { name: "PENTAIR", ticker: "PNR" },
  { name: "T&D HOLDINGS INC", ticker: "8795" },
  { name: "SYMRISE AG", ticker: "SY1" },
  { name: "CLOROX", ticker: "CLX" },
  { name: "TENARIS SA", ticker: "TEN" },
  { name: "TORAY INDUSTRIES INC", ticker: "3402" },
  { name: "RYOHIN KEIKAKU LTD", ticker: "7453" },
  { name: "KUEHNE UND NAGEL INTERNATIONAL AG", ticker: "KNIN" },
  { name: "CAPITALAND INTEGRATED COMMERCIAL T", ticker: "CICT" },
  { name: "COMPUTERSHARE LTD", ticker: "CPU" },
  { name: "GEORGE WESTON LTD", ticker: "WN" },
  { name: "COOPER INC", ticker: "COO" },
  { name: "CHECK POINT SOFTWARE TECHNOLOGIES", ticker: "CHKP" },
  { name: "METSO CORPORATION", ticker: "METSO" },
  { name: "UDR REIT INC", ticker: "UDR" },
  { name: "ALLEGION PLC", ticker: "ALLE" },
  { name: "ZEBRA TECHNOLOGIES CORP CLASS A", ticker: "ZBRA" },
  { name: "RIVIAN AUTOMOTIVE INC CLASS A", ticker: "RIVN" },
  { name: "DRAFTKINGS INC CLASS A", ticker: "DKNG" },
  { name: "FRESNILLO PLC", ticker: "FRES" },
  { name: "BANKINTER SA", ticker: "BKT" },
  { name: "SONOVA HOLDING AG", ticker: "SOON" },
  { name: "AKER BP", ticker: "AKRBP" },
  { name: "WASHINGTON H SOUL PATTINSON & COMP", ticker: "SOL" },
  { name: "INTERTEK GROUP PLC", ticker: "ITRK" },
  { name: "TOAST INC CLASS A", ticker: "TOST" },
  { name: "ATKINSREALIS GROUP INC", ticker: "ATRL" },
  { name: "NEWS CORP CLASS A", ticker: "NWSA" },
  { name: "CARREFOUR SA", ticker: "CA" },
  { name: "CHOCOLADEFABRIKEN LINDT & SPRUENGL", ticker: "LISN" },
  { name: "DOMINOS PIZZA INC", ticker: "DPZ" },
  { name: "ADMIRAL GROUP PLC", ticker: "ADM" },
  { name: "WH GROUP LTD", ticker: "288" },
  { name: "CHOCOLADEFABRIKEN LINDT & SPRUENGL", ticker: "LISP" },
  { name: "INSULET CORP", ticker: "PODD" },
  { name: "GALP ENERGIA SGPS SA CLASS B", ticker: "GALP" },
  { name: "NOMURA RESEARCH INSTITUTE LTD", ticker: "4307" },
  { name: "TFI INTERNATIONAL INC", ticker: "TFII" },
  { name: "BRENNTAG", ticker: "BNR" },
  { name: "JACK HENRY AND ASSOCIATES INC", ticker: "JKHY" },
  { name: "JAPAN EXCHANGE GROUP INC", ticker: "8697" },
  { name: "SEKISUI HOUSE LTD", ticker: "1928" },
  { name: "CNH INDUSTRIAL N.V. NV", ticker: "CNH" },
  { name: "AKZO NOBEL NV", ticker: "AKZA" },
  { name: "HONGKONG LAND HOLDINGS LTD", ticker: "H78" },
  { name: "TMX GROUP LTD", ticker: "X" },
  { name: "PEARSON PLC", ticker: "PSON" },
  { name: "SOLVENTUM CORP", ticker: "SOLV" },
  { name: "ALTAGAS LTD", ticker: "ALA" },
  { name: "TELENOR", ticker: "TEL" },
  { name: "HOCHTIEF AG", ticker: "HOT" },
  { name: "AECOM", ticker: "ACM" },
  { name: "FORTUM", ticker: "FORTUM" },
  { name: "GILDAN ACTIVEWEAR INC", ticker: "GIL" },
  { name: "MOWI", ticker: "MOWI" },
  { name: "FOX CORP CLASS B", ticker: "FOX" },
  { name: "M&G PLC", ticker: "MNG" },
  { name: "ACCOR SA", ticker: "AC" },
  { name: "UNIPOL ASSICURAZIONI SPA", ticker: "UNI" },
  { name: "UNIVERSAL HEALTH SERVICES INC CLAS", ticker: "UHS" },
  { name: "OBIC LTD", ticker: "4684" },
  { name: "SHIMIZU CORP", ticker: "1803" },
  { name: "EISAI LTD", ticker: "4523" },
  { name: "BUNZL", ticker: "BNZL" },
  { name: "XERO LTD", ticker: "XRO" },
  { name: "BUREAU VERITAS SA", ticker: "BVI" },
  { name: "OMV AG", ticker: "OMV" },
  { name: "DAI NIPPON PRINTING LTD", ticker: "7912" },
  { name: "REXEL SA", ticker: "RXL" },
  { name: "TELE2 B", ticker: "TEL2 B" },
  { name: "EPIROC CLASS B", ticker: "EPI B" },
  { name: "EVOLUTION", ticker: "EVO" },
  { name: "GEA GROUP AG", ticker: "G1A" },
  { name: "TRADE DESK INC CLASS A", ticker: "TTD" },
  { name: "BELIMO N AG", ticker: "BEAN" },
  { name: "GRAB HOLDINGS LTD CLASS A", ticker: "GRAB" },
  { name: "KONAMI GROUP CORP", ticker: "9766" },
  { name: "SKF B", ticker: "SKF B" },
  { name: "HUBSPOT INC", ticker: "HUBS" },
  { name: "YOKOGAWA ELECTRIC CORP", ticker: "6841" },
  { name: "ADDTECH CLASS B", ticker: "ADDT B" },
  { name: "LY CORP", ticker: "4689" },
  { name: "BANCO COMERCIAL PORTUGUES SA", ticker: "BCP" },
  { name: "STANTEC INC", ticker: "STN" },
  { name: "YARA INTERNATIONAL", ticker: "YAR" },
  { name: "HEINEKEN HOLDING NV", ticker: "HEIO" },
  { name: "SWEDISH ORPHAN BIOVITRUM", ticker: "SOBI" },
  { name: "OKLO INC CLASS A", ticker: "OKLO" },
  { name: "TRELLEBORG B", ticker: "TREL B" },
  { name: "EUROFINS SCIENTIFIC", ticker: "ERF" },
  { name: "SKANSKA B", ticker: "SKA B" },
  { name: "THE SWATCH GROUP AG", ticker: "UHR" },
  { name: "MINEBEA MITSUMI INC", ticker: "6479" },
  { name: "SHISEIDO LTD", ticker: "4911" },
  { name: "BUILDERS FIRSTSOURCE INC", ticker: "BLDR" },
  { name: "CCL INDUSTRIES INC CLASS B", ticker: "CCL.B" },
  { name: "YOKOHAMA FINANCIAL GROUP INC", ticker: "7186" },
  { name: "APA GROUP UNITS", ticker: "APA" },
  { name: "HENNES & MAURITZ", ticker: "HM B" },
  { name: "MEDIBANK PRIVATE LTD", ticker: "MPL" },
  { name: "GFL ENVIRONMENTAL SUBORDINATE VOTI", ticker: "GFL" },
  { name: "MITSUBISHI CHEMICAL GROUP CORP", ticker: "4188" },
  { name: "MELROSE INDUSTRIES PLC", ticker: "MRO" },
  { name: "ELEMENT FLEET MANAGEMENT CORP", ticker: "EFN" },
  { name: "WEST JAPAN RAILWAY", ticker: "9021" },
  { name: "MARKS AND SPENCER GROUP PLC", ticker: "MKS" },
  { name: "A P MOLLER MAERSK B", ticker: "MAERSK B" },
  { name: "WISE PLC CLASS A", ticker: "WISE" },
  { name: "ORKLA", ticker: "ORK" },
  { name: "SINGAPORE AIRLINES LTD", ticker: "C6L" },
  { name: "YANGZIJIANG SHIPBUILDING (HOLDINGS", ticker: "BS6" },
  { name: "FRESENIUS MEDICAL CARE AG", ticker: "FME" },
  { name: "CAPCOM LTD", ticker: "9697" },
  { name: "NATURGY ENERGY GROUP SA", ticker: "NTGY" },
  { name: "MTR CORPORATION CORP LTD", ticker: "66" },
  { name: "AUCKLAND INTERNATIONAL AIRPORT LTD", ticker: "AIA" },
  { name: "EQUITABLE HOLDINGS INC", ticker: "EQH" },
  { name: "KLEPIERRE REIT SA", ticker: "LI" },
  { name: "CONTINENTAL AG", ticker: "CON" },
  { name: "KEYERA CORP", ticker: "KEY" },
  { name: "UNITED AIRLINES HOLDINGS INC", ticker: "UAL" },
  { name: "COLOPLAST B", ticker: "COLO B" },
  { name: "KNORR BREMSE AG", ticker: "KBX" },
  { name: "EXOR NV", ticker: "EXO" },
  { name: "INFRATIL LTD", ticker: "IFT" },
  { name: "TELECOM ITALIA", ticker: "TIT" },
  { name: "HANKYU HANSHIN HOLDINGS INC", ticker: "9042" },
  { name: "INDUSTRIVARDEN SERIES", ticker: "INDU C" },
  { name: "SIGMA HEALTHCARE LTD", ticker: "SIG" },
  { name: "CAPITALAND ASCENDAS REIT", ticker: "CLAR" },
  { name: "ASSOCIATED BRITISH FOODS PLC", ticker: "ABF" },
  { name: "FUTU HOLDINGS ADR LTD", ticker: "FUTU" },
  { name: "THE LOTTERY CORPORATION LTD", ticker: "TLC" },
  { name: "TRYG", ticker: "TRYG" },
  { name: "ORION CLASS B", ticker: "ORNBV" },
  { name: "UNICHARM CORP", ticker: "8113" },
  { name: "CAE INC", ticker: "CAE" },
  { name: "SECURITAS B", ticker: "SECU B" },
  { name: "HYATT HOTELS CORP CLASS A", ticker: "H" },
  { name: "ACCIONA SA", ticker: "ANA" },
  { name: "IDEMITSU KOSAN LTD", ticker: "5019" },
  { name: "SUBARU CORP", ticker: "7270" },
  { name: "ELIA GROUP SA", ticker: "ELI" },
  { name: "SAMSARA INC CLASS A", ticker: "IOT" },
  { name: "LUNDIN GOLD INC", ticker: "LUG" },
  { name: "ASX LTD", ticker: "ASX" },
  { name: "BEIERSDORF AG", ticker: "BEI" },
  { name: "RAKUTEN GROUP INC", ticker: "4755" },
  { name: "TALANX AG", ticker: "TLX" },
  { name: "DASSAULT AVIATION SA", ticker: "AM" },
  { name: "PANDORA", ticker: "PNDORA" },
  { name: "MITSUBISHI HC CAPITAL INC", ticker: "8593" },
  { name: "GALAXY ENTERTAINMENT GROUP LTD", ticker: "27" },
  { name: "ITALGAS", ticker: "IG" },
  { name: "KINGFISHER PLC", ticker: "KGF" },
  { name: "RAIFFEISEN BANK INTERNATIONAL AG", ticker: "RBI" },
  { name: "NEXON LTD", ticker: "3659" },
  { name: "GROUPE BRUXELLES LAMBERT NV", ticker: "GBLB" },
  { name: "HENDERSON LAND DEVELOPMENT LTD", ticker: "12" },
  { name: "CANADIAN TIRE LTD CLASS A", ticker: "CTC.A" },
  { name: "SHIMADZU CORP", ticker: "7701" },
  { name: "ALSTOM SA", ticker: "ALO" },
  { name: "COREBRIDGE FINANCIAL INC", ticker: "CRBG" },
  { name: "SCHINDLER HOLDING AG", ticker: "SCHN" },
  { name: "SCOUT24 N", ticker: "G24" },
  { name: "SAPUTO INC", ticker: "SAP" },
  { name: "MAGNUM ICE CREAM NV", ticker: "MICC" },
  { name: "YAMAHA MOTOR LTD", ticker: "7272" },
  { name: "INTERNATIONAL AIRLINES GROUP SA", ticker: "IAG" },
  { name: "ZILLOW GROUP INC CLASS C", ticker: "Z" },
  { name: "IPSEN SA", ticker: "IPN" },
  { name: "SCREEN HOLDINGS LTD", ticker: "7735" },
  { name: "LIFCO CLASS B", ticker: "LIFCO B" },
  { name: "HENKEL AG", ticker: "HEN" },
  { name: "SAINSBURY(J) PLC", ticker: "SBRY" },
  { name: "VICINITY CENTRES", ticker: "VCX" },
  { name: "STOCKLAND STAPLED UNITS LTD", ticker: "SGP" },
  { name: "SPIRAX GROUP PLC", ticker: "SPX" },
  { name: "STANDARD LIFE PLC", ticker: "SDLF" },
  { name: "AZRIELI GROUP LTD", ticker: "AZRG" },
  { name: "CAR GROUP LTD", ticker: "CAR" },
  { name: "HKT TRUST AND HKT UNITS LTD", ticker: "6823" },
  { name: "IVANHOE MINES LTD CLASS A", ticker: "IVN" },
  { name: "SARTORIUS PREF AG", ticker: "SRT3" },
  { name: "GETLINK", ticker: "GET" },
  { name: "A P MOLLER MAERSK", ticker: "MAERSK A" },
  { name: "ELISA", ticker: "ELISA" },
  { name: "ISUZU MOTORS LTD", ticker: "7202" },
  { name: "CHEUNG KONG INFRASTRUCTURE HOLDING", ticker: "1038" },
  { name: "QIAGEN NV", ticker: "QIA" },
  { name: "CHIBA BANK LTD", ticker: "8331" },
  { name: "NIBE INDUSTRIER CLASS B", ticker: "NIBE B" },
  { name: "NIPPON BUILDING FUND REIT INC", ticker: "8951" },
  { name: "DESCARTES SYSTEMS GROUP INC", ticker: "DSG" },
  { name: "REA GROUP LTD", ticker: "REA" },
  { name: "WISETECH GLOBAL LTD", ticker: "WTC" },
  { name: "KAWASAKI KISEN LTD", ticker: "9107" },
  { name: "STORA ENSO CLASS R", ticker: "STERV" },
  { name: "OPEN TEXT CORP", ticker: "OTEX" },
  { name: "SNAP INC CLASS A", ticker: "SNAP" },
  { name: "DEUTSCHE LUFTHANSA AG", ticker: "LHA" },
  { name: "AVOLTA AG", ticker: "AVOL" },
  { name: "HORMEL FOODS CORP", ticker: "HRL" },
  { name: "AUTOTRADER GROUP PLC", ticker: "AUTO" },
  { name: "SVENSKA CELLULOSA B", ticker: "SCA B" },
  { name: "KESKO CLASS B", ticker: "KESKOB" },
  { name: "BEIJER REF CLASS B", ticker: "BEIJ B" },
  { name: "SEKISUI CHEMICAL LTD", ticker: "4204" },
  { name: "RENAULT SA", ticker: "RNO" },
  { name: "BARRY CALLEBAUT AG", ticker: "BARN" },
  { name: "OTSUKA CORP", ticker: "4768" },
  { name: "SINO LAND LTD", ticker: "83" },
  { name: "SONIC HEALTHCARE LTD", ticker: "SHL" },
  { name: "WHITBREAD PLC", ticker: "WTB" },
  { name: "BKW N AG", ticker: "BKW" },
  { name: "ICL GROUP LTD", ticker: "ICL" },
  { name: "INDUSTRIVARDEN A", ticker: "INDU A" },
  { name: "JERONIMO MARTINS SA", ticker: "JMT" },
  { name: "TELECOM ITALIA S.P.A.", ticker: "TITR" },
  { name: "NIPPON PAINT HOLDINGS LTD", ticker: "4612" },
  { name: "AMUNDI SA", ticker: "AMUN" },
  { name: "RECORDATI INDUSTRIA CHIMICA E FARM", ticker: "REC" },
  { name: "QANTAS AIRWAYS LTD", ticker: "QAN" },
  { name: "AISIN CORP", ticker: "7259" },
  { name: "EMS-CHEMIE HOLDING AG", ticker: "EMSN" },
  { name: "WHARF REAL ESTATE INVESTMENT COMPA", ticker: "1997" },
  { name: "DR ING HC F PORSCHE PRF AG", ticker: "P911" },
  { name: "SGH LTD", ticker: "SGH" },
  { name: "MATSUKIYOKARA", ticker: "3088" },
  { name: "SONY FINANCIAL GROUP INC", ticker: "8729" },
  { name: "KYOWA KIRIN LTD", ticker: "4151" },
  { name: "ERIE INDEMNITY CLASS A", ticker: "ERIE" },
  { name: "JFE HOLDINGS INC", ticker: "5411" },
  { name: "DELIVERY HERO", ticker: "DHER" },
  { name: "EMPIRE LTD CLASS A", ticker: "EMP.A" },
  { name: "CAPITALAND INVESTMENT LTD", ticker: "9CI" },
  { name: "PORSCHE AUTOMOBIL HOLDING PREF", ticker: "PAH3" },
  { name: "NISSAN MOTOR LTD", ticker: "7201" },
  { name: "EVONIK INDUSTRIES AG", ticker: "EVK" },
  { name: "HENSOLDT AG", ticker: "HAG" },
  { name: "PRO MEDICUS LTD", ticker: "PME" },
  { name: "NICE LTD", ticker: "NICE" },
  { name: "INDUTRADE", ticker: "INDT" },
  { name: "GJENSIDIGE FORSIKRING", ticker: "GJF" },
  { name: "BOLLORE", ticker: "BOL" },
  { name: "TELUS", ticker: "T" },
  { name: "LOTUS BAKERIES NV", ticker: "LOTB" },
  { name: "SEMBCORP INDUSTRIES LTD", ticker: "U96" },
  { name: "BMW PREF AG", ticker: "BMW3" },
  { name: "AIRTEL AFRICA PLC", ticker: "AAF" },
  { name: "WILMAR INTERNATIONAL LTD", ticker: "F34" },
  { name: "SCHRODERS PLC", ticker: "SDR" },
  { name: "BANCA MEDIOLANUM", ticker: "BMED" },
  { name: "LAND SECURITIES GROUP REIT PLC", ticker: "LAND" },
  { name: "COCHLEAR LTD", ticker: "COH" },
  { name: "BROOKFIELD RENEWABLE SUBORDINATE V", ticker: "BEPC" },
  { name: "SARTORIUS STEDIM BIOTECH SA", ticker: "DIM" },
  { name: "ZALANDO", ticker: "ZAL" },
  { name: "FIRSTSERVICE SUBORDINATE VOTING CO", ticker: "FSV" },
  { name: "FINANCIERE DE TUBIZE SA", ticker: "TUB" },
  { name: "SYENSQO NV", ticker: "SYENS" },
  { name: "INDRA SISTEMAS SA", ticker: "IDR" },
  { name: "SHIMANO INC", ticker: "7309" },
  { name: "IGM FINANCIAL INC", ticker: "IGM" },
  { name: "BARRATT REDROW PLC", ticker: "BTRW" },
  { name: "EDP RENOVAVEIS SA", ticker: "EDPR" },
  { name: "LEG IMMOBILIEN N", ticker: "LEG" },
  { name: "SEIBU HOLDINGS INC", ticker: "9024" },
  { name: "MAKITA CORP", ticker: "6586" },
  { name: "SAGAX CLASS B", ticker: "SAGA B" },
  { name: "MAPFRE SA", ticker: "MAP" },
  { name: "KIKKOMAN CORP", ticker: "2801" },
  { name: "CONTACT ENERGY LTD", ticker: "CEN" },
  { name: "HULIC LTD", ticker: "3003" },
  { name: "DIETEREN (D) SA", ticker: "DIE" },
  { name: "TOKYU CORP", ticker: "9005" },
  { name: "VERBUND AG", ticker: "VER" },
  { name: "BC VAUD N", ticker: "BCVN" },
  { name: "CANADIAN UTILITIES LTD CLASS A", ticker: "CU" },
  { name: "DAVIDE CAMPARI MILANO NV", ticker: "CPR" },
  { name: "NIPPON SANSO HOLDINGS CORP", ticker: "4091" },
  { name: "BUZZI", ticker: "BZU" },
  { name: "MERIDIAN ENERGY LTD", ticker: "MEL" },
  { name: "LUNDBERGFORETAGEN CLASS B", ticker: "LUND B" },
  { name: "SODEXO SA", ticker: "SW" },
  { name: "TIS INC", ticker: "3626" },
  { name: "NITORI HOLDINGS LTD", ticker: "9843" },
  { name: "MONOTARO LTD", ticker: "3064" },
  { name: "ENTAIN PLC", ticker: "ENT" },
  { name: "CTS EVENTIM AG", ticker: "EVD" },
  { name: "SANDS CHINA LTD", ticker: "1928" },
  { name: "WHARF (HOLDINGS) LTD", ticker: "4" },
  { name: "DAITO TRUST CONSTRUCTION LTD", ticker: "1878" },
  { name: "DEMANT", ticker: "DEMANT" },
  { name: "SALMAR", ticker: "SALM" },
  { name: "NEMETSCHEK", ticker: "NEM" },
  { name: "SYSMEX CORP", ticker: "6869" },
  { name: "SANRIO LTD", ticker: "8136" },
  { name: "JAPAN POST INSURANCE LTD", ticker: "7181" },
  { name: "INPOST SA", ticker: "INPST" },
  { name: "CSG CLASS A NV", ticker: "CSG" },
  { name: "SWIRE PACIFIC LTD A", ticker: "19" },
  { name: "RANDSTAD HOLDING", ticker: "RAND" },
  { name: "GECINA SA", ticker: "GFC" },
  { name: "M3 INC", ticker: "2413" },
  { name: "FASTIGHETS BALDER CLASS B", ticker: "BALD B" },
  { name: "MONDAYCOM LTD", ticker: "MNDY" },
  { name: "TOHO (TOKYO) LTD", ticker: "9602" },
  { name: "RATIONAL AG", ticker: "RAA" },
  { name: "SOFINA SA", ticker: "SOF" },
  { name: "AGC INC", ticker: "5201" },
  { name: "AYVENS SA", ticker: "AYV" },
  { name: "COVIVIO SA", ticker: "COV" },
  { name: "AEROPORTS DE PARIS SA", ticker: "ADP" },
  { name: "BIOMERIEUX SA", ticker: "BIM" },
  { name: "LATOUR INVESTMENT CLASS B", ticker: "LATO B" },
  { name: "CVC CAPITAL PARTNERS PLC", ticker: "CVC" },
  { name: "HIKARI TSUSHIN INC", ticker: "9435" },
  { name: "ZENSHO HOLDINGS LTD", ticker: "7550" },
  { name: "HOLMEN CLASS B", ticker: "HOLM B" },
  { name: "ROCKWOOL CLASS B", ticker: "ROCK B" },
  { name: "ZOZO INC", ticker: "3092" },
  { name: "GRIFOLS SA CLASS A", ticker: "GRF" },
  { name: "JD SPORTS FASHION PLC", ticker: "JD." },
  { name: "SUNTORY BEVERAGE & FOOD LTD", ticker: "2587" },
  { name: "SITC INTERNATIONAL HOLDINGS LTD", ticker: "1308" },
  { name: "BCE INC", ticker: "BCE" },
  { name: "REDEIA CORPORACION SA", ticker: "RED" },
  { name: "ANA HOLDINGS INC", ticker: "9202" },
  { name: "JAPAN AIRLINES LTD", ticker: "9201" },
  { name: "ORACLE JAPAN CORP", ticker: "4716" },
  { name: "NORION BANK", ticker: "NORION" },
  { name: "KEPPEL REIT UNITS", ticker: "K71U" },
  { name: "CONSTELLATION SOFTWARE INC", ticker: "2299955D" },
];
